### ISSUE TITLE
problems running..

### ISSUE THREAD

**Issue by willwade** [dwadden/wedjat#1]
Looks encouraging this! On initial run this happens though.. 
![screen shot 2016-10-03 at 15 27 46](https://cloud.githubusercontent.com/assets/229352/19040927/09f67216-897e-11e6-8237-88df0860b173.png)

and this is the terminal output:

![screen shot 2016-10-03 at 15 28 48](https://cloud.githubusercontent.com/assets/229352/19040942/19b5763e-897e-11e6-8d56-9c95502ade42.png)

Is there any idea to separate the access method (a look up) from the AAC system? That would make a bit more sense so we could use other systems e.g. https://github.com/ipomoena/dasher 👍

**Comment by ylh888** [comment]
Hi Will,

Thank you for trying this software. I'm having the same issue.

The last good commit is https://github.com/dwadden/wedjat/commit/97e6052e677e1d60c9c388dc5f621875e274b27e
from Sep 10.

if you run: git checkout  97e6052

you will be able to try that version with the command: node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron .

Cheers.

**Comment by dwadden** [comment]
I think I fixed it. Try pulling and let me know if the latest version works.

**Comment by ylh888** [comment]
Excellent. It does work. Thanks, Dave.

Another team has taken the code and made some changes. I have also added a Spanish option as there is a LIS user testing the software.

The menu has been re-organized somewhat.

Will make a new branch.

**Comment by dwadden** [comment]
Great, glad it works. I have a bit of time to do code maintenance etc if it would be helpful. Let me know.

**Comment by ylh888** [comment]
Please check out the Project Vive branch. I'll write separately to brief you on what we plan to do next. Appreciate your offer of help.

**Comment by dwadden** [comment]
Sounds good.

**Comment by willwade** [comment]
Looking great folks. Thanks for the fixes!
